### ISSUE TITLE
Ambigous call to signbit() in MS Visual Studio

### ISSUE THREAD

**Issue by marius-sucan** [signetica/SunRise#3]
Hello!

I wanted to test the library, but I get  «ambigous call to signbit()» error when I compile the code in MS Visual Studio 2019. It is on line 178, 180 and 182, in SunRise.cpp.

How to fix this? Thank you .

Best regards, Marius.

**Comment by signetica** [comment]
I searched a little for what might be behind this.

Microsoft interpreted the standard as not supporting integer arguments to these math functions.  When it was pointed out this is probably incorrect, they decided that they'd someday file a request to change the standard.

In any case deciding if an integer is positive is not  difficult in C, and so I'll fix it later today when I'm  near the computer.  I'll let you know when it's ready and you can test it  for me.

If you want to test the software quickly, before I can fix your problem, just cast the argument to signbit() to a float, e.g. replace signbit(integer) by signbit((float)integer) whenever your compiler complains, and your  code should compile.

Thanks,
Cyrus

**Comment by marius-sucan** [comment]
Thank you for the quick reply.

I already tested it partially, I just commented those sections and the calculated values for sunset/sunrise seemed to be correct. I know it was a dirty thing, I have read the comments and I know it just happens I am in a region of the globe where sunrise/sunsets occur within the given interval of 48 hours. I will wait for your fix and then try it some more.

Best regards, Marius.

**Comment by signetica** [comment]
Ok, I have avoided using signbit(int) to keep Microsoft's compiler happy.

Try it out and let me know if this solves your problem.

**Comment by marius-sucan** [comment]
Thank you very much . It works well. 

Please note, MoonRise.cpp has the same issue. I may use both in my Church Bells Tower project to indicate these events.

Best regards, Marius.

**Comment by signetica** [comment]
Ok, I've made the final update regarding this issue (unless you notice a problem).  I've also updated the  MoonRise class.  If all is well go ahead and close the issue, and I'll make a new tag/release.

Thanks for reporting the problem, and I hope it works out for you.

**Comment by marius-sucan** [comment]
Thank you very much!
